version: "2.1"

services:
  timecheck:
    image: timecheck
    build: .
    environment:
      - TOKEN=476636678:AAEUsDFZI_qmhftx1L0PjIxoD0M3EzzZI18
      - ENV=development
      - PORT=3000
    ports:
      - 3000:3000
    restart: always
